"""
generate_eps.py
---------------
Reads wave_spawns_full.csv and wave_spawns_split.csv and outputs:

  WaveSpawnsFull.eps        -> waveSpawnsFull1, waveSpawnsFull2
  HardModeSpawnsFull.eps    -> waveSpawnsFullHard1..4
  WaveSpawnsSplit.eps       -> WaveSpawnsSplit1, WaveSpawnsSplit2
  HardModeSpawnsSplit.eps   -> waveSpawnsSplitHard1..4
  wave_spawns_indexes.eps   -> waveSpawnsUnitIndex

Unit order and round count are read dynamically from the CSV headers.
All CSV files must have identical headers or the script will error and pause.
"""

import csv
import os
import sys

# ── Reserved columns that are not unit names ──────────────────────────────────
RESERVED_COLS = {'Round', 'Location', 'Hard Mode'}

# ── CSV files to process ──────────────────────────────────────────────────────
CSV_FILES = [
	"wave_spawns_full.csv",
	"wave_spawns_split.csv",
]


# ── Read unit order from a single CSV's headers ───────────────────────────────
def get_headers(path):
	with open(path, newline='', encoding='utf-8') as f:
		reader = csv.reader(f)
		headers = next(reader)
	return [h.strip() for h in headers if h.strip() not in RESERVED_COLS]


# ── Validate all CSVs share the same header, return unit order ────────────────
def validate_and_load_unit_order():
	found = {}
	for path in CSV_FILES:
		if not os.path.exists(path):
			print(f"WARNING: {path} not found, skipping header check.")
			continue
		found[path] = get_headers(path)

	if not found:
		print("ERROR: No CSV files found.")
		input("Press Enter to exit...")
		sys.exit(1)

	files   = list(found.keys())
	headers = list(found.values())
	ref     = headers[0]

	mismatches = []
	for i in range(1, len(files)):
		if headers[i] != ref:
			mismatches.append(
				f"  {files[0]}:\n    {ref}\n"
				f"  {files[i]}:\n    {headers[i]}"
			)

	if mismatches:
		print("\n" + "=" * 60)
		print("ERROR: CSV headers do not match!\n")
		for m in mismatches:
			print(m)
		print("=" * 60)
		input("\nPress Enter to exit...")
		sys.exit(1)

	print(f"Headers validated across {len(files)} CSV file(s) — all match.")
	print(f"Unit order: {len(ref)} units loaded from {files[0]}")
	return ref


# ── Load unit order at import time ────────────────────────────────────────────
UNIT_ORDER = validate_and_load_unit_order()
NUM_UNITS  = len(UNIT_ORDER)


# ── Load a CSV into structured dicts ──────────────────────────────────────────
def load_csv(path):
	spawner1  = {}
	spawner2  = {}
	hard_opts = {}

	with open(path, newline='', encoding='utf-8') as f:
		reader = csv.DictReader(f)
		for row in reader:
			raw_round = row['Round'].strip()
			location  = row['Location'].strip()
			hard_mode = row['Hard Mode'].strip()

			try:
				rnum = int(raw_round)
			except ValueError:
				continue

			unit_counts = {}
			for unit in UNIT_ORDER:
				val = row.get(unit, '').strip()
				unit_counts[unit] = int(val) if val else 0

			if hard_mode == '':
				if location == 'spawner':
					spawner1[rnum] = unit_counts
				elif location == 'spawner2':
					spawner2[rnum] = unit_counts
			elif hard_mode.startswith('option'):
				opt_idx = int(hard_mode.split()[-1]) - 1
				if rnum not in hard_opts:
					hard_opts[rnum] = [{} for _ in range(4)]
				hard_opts[rnum][opt_idx] = unit_counts

	all_rounds = set(list(spawner1.keys()) + list(spawner2.keys()) + list(hard_opts.keys()))
	max_rounds = max(all_rounds) if all_rounds else 1
	return spawner1, spawner2, hard_opts, max_rounds


# ── Inline comment: list non-zero units ───────────────────────────────────────
def unit_comment(unit_dict):
	parts = [f"{unit_dict[u]} {u}" for u in UNIT_ORDER if unit_dict.get(u, 0)]
	return ', '.join(parts) if parts else "Nothing"


# ── Single VArray line ────────────────────────────────────────────────────────
def varray_line(unit_dict, comment_prefix):
	values  = [str(unit_dict.get(u, 0)).rjust(2) for u in UNIT_ORDER]
	comment = unit_comment(unit_dict)
	return f"\tVArray({', '.join(values)}),  // {comment_prefix}  {comment}"


# ── Full EUDVArray block ──────────────────────────────────────────────────────
def build_block(var_name, round_dict, comment_fn, max_rounds):
	lines = [f"const {var_name} = EUDVArray({max_rounds}, EUDVArray({NUM_UNITS}))(list("]
	for rnum in range(1, max_rounds + 1):
		unit_dict = round_dict.get(rnum, {u: 0 for u in UNIT_ORDER})
		lines.append(varray_line(unit_dict, comment_fn(rnum)))
	lines.append("));")
	return '\n'.join(lines)


# ── File header with unit index reference ─────────────────────────────────────
def file_header(source_csv):
	lines = [
		f"// Auto-generated by generate_eps.py  (source: {source_csv})",
		f"// Unit index order (0-{NUM_UNITS - 1}):",
	]
	for i, u in enumerate(UNIT_ORDER):
		lines.append(f"//   [{i:2d}] {u}")
	lines.append("")
	return '\n'.join(lines)


# ── Write normal + hard mode files for one CSV ────────────────────────────────
def write_eps(csv_path, normal_eps, hard_eps, name1, name2, hard_prefix):
	spawner1, spawner2, hard_opts, max_rounds = load_csv(csv_path)
	src = os.path.basename(csv_path)
	print(f"  {src}: {max_rounds} rounds detected")

	# Normal spawns
	with open(normal_eps, 'w', encoding='utf-8') as f:
		f.write(file_header(src))
		f.write('\n')
		f.write(build_block(name1, spawner1, lambda r: f"Round {r:<4}", max_rounds))
		f.write('\n\n')
		f.write(build_block(name2, spawner2, lambda r: f"Round {r:<4}", max_rounds))
		f.write('\n')
	print(f"Written: {normal_eps}  ({name1}, {name2})")

	# Hard mode spawns
	with open(hard_eps, 'w', encoding='utf-8') as f:
		f.write(file_header(src))
		f.write('\n')
		for opt_idx in range(4):
			opt_dict = {}
			for rnum in range(1, max_rounds + 1):
				if rnum in hard_opts and opt_idx < len(hard_opts[rnum]):
					opt_dict[rnum] = hard_opts[rnum][opt_idx]
				else:
					opt_dict[rnum] = {u: 0 for u in UNIT_ORDER}

			var_name = f"{hard_prefix}{opt_idx + 1}"
			f.write(build_block(
				var_name, opt_dict,
				lambda r, o=opt_idx: f"Round {r:<4} hard option {o + 1},",
				max_rounds
			))
			f.write('\n\n')
	print(f"Written: {hard_eps}  ({hard_prefix}1..4)")


# ── Generate wave_spawns_indexes.eps ──────────────────────────────────────────
def write_indexes_eps():
	with open("wave_spawns_indexes.eps", 'w', encoding='utf-8') as f:
		f.write("// Auto-generated by generate_eps.py\n")
		f.write(f"// Unit integer IDs in UNIT_ORDER sequence (0-{NUM_UNITS - 1})\n")
		f.write("// Usage:\n")
		f.write("//   var unitId = waveSpawnsUnitIndex[i];\n")
		f.write("//   CreateUnitWithProperties(count, unitId, \"spawner\", player, UnitProperty());\n")
		f.write("\n")
		f.write(f"const waveSpawnsUnitIndex = EUDVArray({NUM_UNITS})(list(\n")
		for i, unit in enumerate(UNIT_ORDER):
			comma = "," if i < NUM_UNITS - 1 else ""
			f.write(f'\t$U("{unit}"){comma}  // [{i:2d}] {unit}\n')
		f.write("));\n")
	print("Written: wave_spawns_indexes.eps")


# ── Entry point ───────────────────────────────────────────────────────────────
if __name__ == '__main__':
	write_eps(
		csv_path    = "wave_spawns_full.csv",
		normal_eps  = "WaveSpawnsFull.eps",
		hard_eps    = "HardModeSpawnsFull.eps",
		name1       = "waveSpawnsFull1",
		name2       = "waveSpawnsFull2",
		hard_prefix = "waveSpawnsFullHard",
	)

	write_eps(
		csv_path    = "wave_spawns_split.csv",
		normal_eps  = "WaveSpawnsSplit.eps",
		hard_eps    = "HardModeSpawnsSplit.eps",
		name1       = "WaveSpawnsSplit1",
		name2       = "WaveSpawnsSplit2",
		hard_prefix = "waveSpawnsSplitHard",
	)

	write_indexes_eps()

	print("\nDone!")
	print("  WaveSpawnsFull.eps        — waveSpawnsFull1, waveSpawnsFull2")
	print("  HardModeSpawnsFull.eps    — waveSpawnsFullHard1..4")
	print("  WaveSpawnsSplit.eps       — WaveSpawnsSplit1, WaveSpawnsSplit2")
	print("  HardModeSpawnsSplit.eps   — waveSpawnsSplitHard1..4")
	print("  wave_spawns_indexes.eps   — waveSpawnsUnitIndex")
