"""
generate_eps.py
---------------
Reads wave_spawns_full.csv and wave_spawns_split.csv and outputs:

  WaveSpawnsFull.eps        -> waveSpawnsFull1, waveSpawnsFull2
  HardModeSpawnsFull.eps    -> waveSpawnsFullHard1..4
  WaveSpawnsSplit.eps       -> WaveSpawnsSplit1, WaveSpawnsSplit2
  HardModeSpawnsSplit.eps   -> waveSpawnsSplitHard1..4
  wave_spawns_indexes.eps   -> waveSpawnsUnitIndex

Unit order and round count are read dynamically from the CSV headers.
All CSV files must have identical headers or the script will error and pause.
"""

import csv
import os
import sys

# ── Reserved columns that are not unit names ──────────────────────────────────
RESERVED_COLS = {'Round', 'Location', 'Hard Mode'}

# ── CSV files to process ──────────────────────────────────────────────────────
CSV_FILES = [
	"wave_spawns_full.csv",
	"wave_spawns_split.csv",
]


# ── Read unit order from a single CSV's headers ───────────────────────────────
def get_headers(path):
	with open(path, newline='', encoding='utf-8') as f:
		reader = csv.reader(f)
		headers = next(reader)
	return [h.strip() for h in headers if h.strip() not in RESERVED_COLS]


# ── Validate all CSVs share the same header, return unit order ────────────────
def validate_and_load_unit_order():
	found = {}
	for path in CSV_FILES:
		if not os.path.exists(path):
			print(f"WARNING: {path} not found, skipping header check.")
			continue
		found[path] = get_headers(path)

	if not found:
		print("ERROR: No CSV files found.")
		input("Press Enter to exit...")
		sys.exit(1)

	files   = list(found.keys())
	headers = list(found.values())
	ref     = headers[0]

	mismatches = []
	for i in range(1, len(files)):
		if headers[i] != ref:
			mismatches.append(
				f"  {files[0]}:\n    {ref}\n"
				f"  {files[i]}:\n    {headers[i]}"
			)

	if mismatches:
		print("\n" + "=" * 60)
		print("ERROR: CSV headers do not match!\n")
		for m in mismatches:
			print(m)
		print("=" * 60)
		input("\nPress Enter to exit...")
		sys.exit(1)

	print(f"Headers validated across {len(files)} CSV file(s) — all match.")
	print(f"Unit order: {len(ref)} units loaded from {files[0]}")
	return ref


# ── Load unit order at import time ────────────────────────────────────────────
UNIT_ORDER = validate_and_load_unit_order()
NUM_UNITS  = len(UNIT_ORDER)


# ── Load a CSV into structured dicts ──────────────────────────────────────────
def load_csv(path):
	spawner1  = {}
	spawner2  = {}
	hard_opts = {}

	with open(path, newline='', encoding='utf-8') as f:
		reader = csv.DictReader(f)
		for row in reader:
			raw_round = row['Round'].strip()
			location  = row['Location'].strip()
			hard_mode = row['Hard Mode'].strip()

			try:
				rnum = int(raw_round)
			except ValueError:
				continue

			unit_counts = {}
			for unit in UNIT_ORDER:
				val = row.get(unit, '').strip()
				unit_counts[unit] = int(val) if val else 0

			if hard_mode == '':
				if location == 'spawner':
					spawner1[rnum] = unit_counts
				elif location == 'spawner2':
					spawner2[rnum] = unit_counts
			elif hard_mode.startswith('option'):
				opt_idx = int(hard_mode.split()[-1]) - 1
				if rnum not in hard_opts:
					hard_opts[rnum] = [{} for _ in range(4)]
				hard_opts[rnum][opt_idx] = unit_counts

	all_rounds = set(list(spawner1.keys()) + list(spawner2.keys()) + list(hard_opts.keys()))
	max_rounds = max(all_rounds) if all_rounds else 1
	return spawner1, spawner2, hard_opts, max_rounds


# ── Inline comment: list non-zero units ───────────────────────────────────────
def unit_comment(unit_dict):
	parts = [f"{unit_dict[u]} {u}" for u in UNIT_ORDER if unit_dict.get(u, 0)]
	return ', '.join(parts) if parts else "Nothing"


# ── Single VArray line ────────────────────────────────────────────────────────
def varray_line(unit_dict, comment_prefix):
	values  = [str(unit_dict.get(u, 0)).rjust(2) for u in UNIT_ORDER]
	comment = unit_comment(unit_dict)
	return f"\tVArray({', '.join(values)}),  // {comment_prefix}  {comment}"


# ── Full EUDVArray block ──────────────────────────────────────────────────────
def build_block(var_name, round_dict, comment_fn, max_rounds):
	lines = [f"const {var_name} = EUDVArray({max_rounds}, EUDVArray({NUM_UNITS}))(list("]
	for rnum in range(1, max_rounds + 1):
		unit_dict = round_dict.get(rnum, {u: 0 for u in UNIT_ORDER})
		lines.append(varray_line(unit_dict, comment_fn(rnum)))
	lines.append("));")
	return '\n'.join(lines)


# ── File header with unit index reference ─────────────────────────────────────
def file_header(source_csv):
	lines = [
		f"// Auto-generated by generate_eps.py  (source: {source_csv})",
		f"// Unit index order (0-{NUM_UNITS - 1}):",
	]
	for i, u in enumerate(UNIT_ORDER):
		lines.append(f"//   [{i:2d}] {u}")
	lines.append("")
	return '\n'.join(lines)


# ── Write normal + hard mode files for one CSV ────────────────────────────────
def write_eps(csv_path, normal_eps, hard_eps, name1, name2, hard_prefix):
	spawner1, spawner2, hard_opts, max_rounds = load_csv(csv_path)
	src = os.path.basename(csv_path)
	print(f"  {src}: {max_rounds} rounds detected")

	# Normal spawns
	with open(normal_eps, 'w', encoding='utf-8') as f:
		f.write(file_header(src))
		f.write('\n')
		f.write(build_block(name1, spawner1, lambda r: f"Round {r:<4}", max_rounds))
		f.write('\n\n')
		f.write(build_block(name2, spawner2, lambda r: f"Round {r:<4}", max_rounds))
		f.write('\n')
	print(f"Written: {normal_eps}  ({name1}, {name2})")

	# Hard mode spawns
	with open(hard_eps, 'w', encoding='utf-8') as f:
		f.write(file_header(src))
		f.write('\n')
		for opt_idx in range(4):
			opt_dict = {}
			for rnum in range(1, max_rounds + 1):
				if rnum in hard_opts and opt_idx < len(hard_opts[rnum]):
					opt_dict[rnum] = hard_opts[rnum][opt_idx]
				else:
					opt_dict[rnum] = {u: 0 for u in UNIT_ORDER}

			var_name = f"{hard_prefix}{opt_idx + 1}"
			f.write(build_block(
				var_name, opt_dict,
				lambda r, o=opt_idx: f"Round {r:<4} hard option {o + 1},",
				max_rounds
			))
			f.write('\n\n')
	print(f"Written: {hard_eps}  ({hard_prefix}1..4)")


# ── Build wave notification strings for all rounds ────────────────────────────
def build_wave_strings(csv_path):
	"""
	Returns a dict: round_num -> list of strings (rows), each <= 60 chars.
	e.g. { 1: ["Wave 1: 30x Zerg Ultralisk,", "20x Terran Firebat"] }
	Combines spawner1 + spawner2 counts per unit.
	"""
	spawner1, spawner2, _, max_rounds = load_csv(csv_path)
	result = {}
	for rnum in range(1, max_rounds + 1):
		s1 = spawner1.get(rnum, {u: 0 for u in UNIT_ORDER})
		s2 = spawner2.get(rnum, {u: 0 for u in UNIT_ORDER})

		parts = []
		for unit in UNIT_ORDER:
			total = s1.get(unit, 0) + s2.get(unit, 0)
			if total > 0:
				parts.append(f"{total}x {unit}")

		if not parts:
			result[rnum] = [f"Wave {rnum}: Nothing"]
			continue

		# Split into rows of <= 60 chars
		header = f"Wave {rnum}:"
		rows = []
		current = header
		for i, part in enumerate(parts):
			sep = " " if current == header else ", "
			candidate = current + sep + part
			if len(candidate) <= 60:
				current = candidate
			else:
				rows.append(current + ("," if i > 0 else ""))
				current = "  " + part  # indent continuation lines
		rows.append(current)
		result[rnum] = rows

	return result, max_rounds


# ── Build split (per-player) wave notification strings ────────────────────────
def build_wave_strings_split(csv_path):
	"""
	Like build_wave_strings but uses the split CSV and prefixes each wave with
	"Wave N [per player]:" to indicate per-player counts.
	"""
	spawner1, spawner2, _, max_rounds = load_csv(csv_path)
	result = {}
	for rnum in range(1, max_rounds + 1):
		s1 = spawner1.get(rnum, {u: 0 for u in UNIT_ORDER})
		s2 = spawner2.get(rnum, {u: 0 for u in UNIT_ORDER})

		parts = []
		for unit in UNIT_ORDER:
			total = s1.get(unit, 0) + s2.get(unit, 0)
			if total > 0:
				parts.append(f"{total}x {unit}")

		if not parts:
			result[rnum] = [f"Wave {rnum} [per player]: Nothing"]
			continue

		header = f"Wave {rnum} [per player]:"
		rows = []
		current = header
		for i, part in enumerate(parts):
			sep = " " if current == header else ", "
			candidate = current + sep + part
			if len(candidate) <= 60:
				current = candidate
			else:
				rows.append(current + ("," if i > 0 else ""))
				current = "  " + part
		rows.append(current)
		result[rnum] = rows

	return result, max_rounds


# ── Build hard-mode notification strings for one option ───────────────────────
def build_hard_wave_strings(csv_path, opt_idx, is_split=False):
	"""
	Returns hard mode notification strings for a single option index (0-3).
	Full mode:  count * 2 because the game spawns the same count at both spawners.
	Split mode: count as-is (per-player value, no doubling).
	Rounds with no hard extras for that option return an empty list.
	"""
	_, _, hard_opts, max_rounds = load_csv(csv_path)
	result = {}
	for rnum in range(1, max_rounds + 1):
		if rnum in hard_opts and opt_idx < len(hard_opts[rnum]):
			unit_dict = hard_opts[rnum][opt_idx]
		else:
			unit_dict = {u: 0 for u in UNIT_ORDER}

		parts = []
		for unit in UNIT_ORDER:
			count = unit_dict.get(unit, 0)
			total = count if is_split else count * 2
			if total > 0:
				parts.append(f"{total}x {unit}")

		if not parts:
			result[rnum] = []
			continue

		header = "Hard [per player]:" if is_split else "Hard extras:"
		rows = []
		current = header
		for i, part in enumerate(parts):
			sep = " " if current == header else ", "
			candidate = current + sep + part
			if len(candidate) <= 60:
				current = candidate
			else:
				rows.append(current + ",")
				current = "  " + part
		rows.append(current)
		result[rnum] = rows

	return result, max_rounds


# ── Write a waveNotifyStrings EUDVArray block ─────────────────────────────────
def write_notify_block(f, var_name, strings_dict, max_rounds, max_rows):
	"""Writes one const EUDVArray(max_rounds, EUDVArray(max_rows)) block."""
	f.write(f"const {var_name} = EUDVArray({max_rounds}, EUDVArray({max_rows}))(list(\n")
	for rnum in range(1, max_rounds + 1):
		rows = list(strings_dict.get(rnum, []))
		while len(rows) < max_rows:
			rows.append(0)
		row_strs = []
		for row in rows:
			if row == 0:
				row_strs.append("0")
			else:
				escaped = row.replace('"', '\\"')
				row_strs.append(f'$T("{escaped}")')
		comma = "," if rnum < max_rounds else ""
		f.write(f"\tVArray({', '.join(row_strs)}){comma}  // Round {rnum}\n")
	f.write("));\n")


# ── Generate wave_spawns_indexes.eps ──────────────────────────────────────────
def write_indexes_eps():
	# ── Full wave notification strings ───────────────────────────────────────
	wave_strings, max_rounds = build_wave_strings("wave_spawns_full.csv")
	max_rows = max(len(rows) for rows in wave_strings.values())

	# ── Split (per-player) wave notification strings ─────────────────────────
	split_strings, _ = build_wave_strings_split("wave_spawns_split.csv")
	max_rows_split = max(len(rows) for rows in split_strings.values())

	# ── Hard mode full notification strings (4 options) ──────────────────────
	hard_full = [build_hard_wave_strings("wave_spawns_full.csv", i, is_split=False)[0]
	             for i in range(4)]
	hard_full_row_lens = [len(rows) for s in hard_full for rows in s.values() if rows]
	max_rows_hard = max(hard_full_row_lens) if hard_full_row_lens else 1

	# ── Hard mode split notification strings (4 options) ─────────────────────
	hard_split = [build_hard_wave_strings("wave_spawns_split.csv", i, is_split=True)[0]
	              for i in range(4)]
	hard_split_row_lens = [len(rows) for s in hard_split for rows in s.values() if rows]
	max_rows_hard_split = max(hard_split_row_lens) if hard_split_row_lens else 1

	with open("wave_spawns_indexes.eps", 'w', encoding='utf-8') as f:
		f.write("// Auto-generated by generate_eps.py\n")
		f.write(f"// Unit integer IDs in UNIT_ORDER sequence (0-{NUM_UNITS - 1})\n")
		f.write("// Usage:\n")
		f.write("//   var unitId = waveSpawnsUnitIndex[i];\n")
		f.write("//   CreateUnitWithProperties(count, unitId, \"spawner\", player, UnitProperty());\n")
		f.write("\n")
		f.write(f"const NUM_UNITS = {NUM_UNITS};  // auto-generated by generate_eps.py\n\n")

		# Unit ID array
		f.write(f"const waveSpawnsUnitIndex = EUDVArray({NUM_UNITS})(list(\n")
		for i, unit in enumerate(UNIT_ORDER):
			comma = "," if i < NUM_UNITS - 1 else ""
			f.write(f'\t$U("{unit}"){comma}  // [{i:2d}] {unit}\n')
		f.write("));\n\n")

		# ── Normal full wave strings ──────────────────────────────────────────
		f.write("// Pre-built wave notification strings (full counts)\n")
		f.write("// waveNotifyStrings[round][row] — use WAVE_NOTIFY_ROWS for row count\n")
		f.write(f"const WAVE_NOTIFY_ROWS = {max_rows};\n\n")
		write_notify_block(f, "waveNotifyStrings", wave_strings, max_rounds, max_rows)
		f.write("\n")

		# ── Split (per-player) wave strings ──────────────────────────────────
		f.write("// Pre-built split (per-player) wave notification strings\n")
		f.write("// waveNotifyStringsSplit[round][row] — use WAVE_NOTIFY_ROWS_SPLIT for row count\n")
		f.write(f"const WAVE_NOTIFY_ROWS_SPLIT = {max_rows_split};\n\n")
		write_notify_block(f, "waveNotifyStringsSplit", split_strings, max_rounds, max_rows_split)
		f.write("\n")

		# ── Hard mode full strings (options 1-4) ─────────────────────────────
		f.write("// Hard mode extra spawn notification strings (full counts, both spawners)\n")
		f.write("// waveNotifyStringsHard1..4[round][row] — use WAVE_NOTIFY_ROWS_HARD for row count\n")
		f.write(f"const WAVE_NOTIFY_ROWS_HARD = {max_rows_hard};\n\n")
		for opt_idx in range(4):
			write_notify_block(f, f"waveNotifyStringsHard{opt_idx + 1}",
			                   hard_full[opt_idx], max_rounds, max_rows_hard)
			f.write("\n")

		# ── Hard mode split strings (options 1-4) ────────────────────────────
		f.write("// Hard mode extra spawn notification strings (per-player split counts)\n")
		f.write("// waveNotifyStringsHardSplit1..4[round][row] — use WAVE_NOTIFY_ROWS_HARD_SPLIT\n")
		f.write(f"const WAVE_NOTIFY_ROWS_HARD_SPLIT = {max_rows_hard_split};\n\n")
		for opt_idx in range(4):
			write_notify_block(f, f"waveNotifyStringsHardSplit{opt_idx + 1}",
			                   hard_split[opt_idx], max_rounds, max_rows_hard_split)
			if opt_idx < 3:
				f.write("\n")

	print("Written: wave_spawns_indexes.eps")
	print(f"  {max_rounds} rounds, up to {max_rows} rows/round (full)")
	print(f"  {max_rounds} rounds, up to {max_rows_split} rows/round (split)")
	print(f"  Hard full: {max_rows_hard} rows/round  |  Hard split: {max_rows_hard_split} rows/round")


# ── Entry point ───────────────────────────────────────────────────────────────
if __name__ == '__main__':
	write_eps(
		csv_path    = "wave_spawns_full.csv",
		normal_eps  = "WaveSpawnsFull.eps",
		hard_eps    = "HardModeSpawnsFull.eps",
		name1       = "waveSpawnsFull1",
		name2       = "waveSpawnsFull2",
		hard_prefix = "waveSpawnsFullHard",
	)

	write_eps(
		csv_path    = "wave_spawns_split.csv",
		normal_eps  = "WaveSpawnsSplit.eps",
		hard_eps    = "HardModeSpawnsSplit.eps",
		name1       = "WaveSpawnsSplit1",
		name2       = "WaveSpawnsSplit2",
		hard_prefix = "waveSpawnsSplitHard",
	)

	write_indexes_eps()

	print("\nDone!")
	print("  WaveSpawnsFull.eps        — waveSpawnsFull1, waveSpawnsFull2")
	print("  HardModeSpawnsFull.eps    — waveSpawnsFullHard1..4")
	print("  WaveSpawnsSplit.eps       — WaveSpawnsSplit1, WaveSpawnsSplit2")
	print("  HardModeSpawnsSplit.eps   — waveSpawnsSplitHard1..4")
	print("  wave_spawns_indexes.eps   — waveSpawnsUnitIndex,")
	print("                              waveNotifyStrings, waveNotifyStringsSplit,")
	print("                              waveNotifyStringsHard1..4,")
	print("                              waveNotifyStringsHardSplit1..4")
