"""
generate_wave_spawns_array_eps.py
---------------------------------
Reads wave_spawns.csv and writes wave_spawns_array.eps.

CSV format:
	Wave,WaveDelayMS,<unit columns...>

Each row is one spawn batch. WaveDelayMS is the delay BEFORE that row spawns.
The first row of each wave should be 0 so it spawns immediately.
"""

import csv
import os
import sys

CSV_PATH = "wave_spawns.csv"
OUT_PATH = "wave_spawns_array.eps"
RESERVED_COLS = {"Wave", "WaveDelayMS"}
FRAMES_PER_SECOND = 24


def ms_to_frames(ms):
	return int(ms) * FRAMES_PER_SECOND // 1000


def load_csv(path):
	if not os.path.exists(path):
		print(f"ERROR: {path} not found")
		sys.exit(1)

	with open(path, newline="", encoding="utf-8") as f:
		reader = csv.DictReader(f)
		unit_order = [h.strip() for h in reader.fieldnames if h.strip() not in RESERVED_COLS]
		rows = []
		for raw in reader:
			if not raw.get("Wave", "").strip():
				continue
			wave = int(raw["Wave"].strip())
			delay_ms = int(raw.get("WaveDelayMS", "0").strip() or 0)
			counts = []
			for unit in unit_order:
				val = raw.get(unit, "").strip()
				counts.append(int(val) if val else 0)
			rows.append((wave, delay_ms, counts))
	return unit_order, rows


def unit_comment(unit_order, counts):
	parts = []
	for unit, count in zip(unit_order, counts):
		if count:
			parts.append(f"{count}x {unit}")
	return ", ".join(parts) if parts else "No units"


def main():
	unit_order, rows = load_csv(CSV_PATH)
	if not rows:
		print("ERROR: No spawn rows found")
		sys.exit(1)

	max_wave = max(wave for wave, _, _ in rows)
	first_row = [0] * (max_wave + 1)
	row_count = [0] * (max_wave + 1)
	for idx, (wave, _, _) in enumerate(rows):
		if row_count[wave] == 0:
			first_row[wave] = idx
		row_count[wave] += 1

	with open(OUT_PATH, "w", encoding="utf-8") as f:
		f.write("// Auto-generated by generate_wave_spawns_array_eps.py\n")
		f.write(f"// Source: {CSV_PATH}\n")
		f.write("// WaveDelayMS is converted to Brood War frames at 24 frames/sec.\n\n")
		f.write(f"const NUM_WAVES = {max_wave};\n")
		f.write(f"const NUM_WAVE_ROWS = {len(rows)};\n")
		f.write(f"const NUM_WAVE_UNITS = {len(unit_order)};\n\n")

		f.write("// Unit integer IDs in CSV column order.\n")
		f.write(f"const waveSpawnUnitIndex = EUDVArray({len(unit_order)})(list(\n")
		for i, unit in enumerate(unit_order):
			comma = "," if i < len(unit_order) - 1 else ""
			f.write(f'\t$U("{unit}"){comma}  // [{i:2d}] {unit}\n')
		f.write("));\n\n")

		f.write("// First flattened row index for each wave. Index 0 is unused.\n")
		f.write(f"const waveSpawnFirstRow = EUDVArray({max_wave + 1})(list(\n")
		for wave in range(max_wave + 1):
			comma = "," if wave < max_wave else ""
			label = "unused" if wave == 0 else f"Wave {wave}"
			f.write(f"\t{first_row[wave]}{comma}  // {label}\n")
		f.write("));\n\n")

		f.write("// Number of flattened rows in each wave. Index 0 is unused.\n")
		f.write(f"const waveSpawnRowCount = EUDVArray({max_wave + 1})(list(\n")
		for wave in range(max_wave + 1):
			comma = "," if wave < max_wave else ""
			label = "unused" if wave == 0 else f"Wave {wave}"
			f.write(f"\t{row_count[wave]}{comma}  // {label}\n")
		f.write("));\n\n")

		f.write("// Delay before each flattened spawn row, in frames.\n")
		f.write(f"const waveSpawnDelayFrames = EUDVArray({len(rows)})(list(\n")
		for i, (wave, delay_ms, counts) in enumerate(rows):
			comma = "," if i < len(rows) - 1 else ""
			f.write(f"\t{ms_to_frames(delay_ms)}{comma}  // row {i}, wave {wave}, {delay_ms}ms\n")
		f.write("));\n\n")

		f.write("// Spawn counts by flattened row and unit index.\n")
		f.write(f"const waveSpawnCounts = EUDVArray({len(rows)}, EUDVArray({len(unit_order)}))(list(\n")
		for i, (wave, delay_ms, counts) in enumerate(rows):
			comma = "," if i < len(rows) - 1 else ""
			vals = ", ".join(str(v).rjust(2) for v in counts)
			f.write(f"\tVArray({vals}){comma}  // row {i}, wave {wave}: {unit_comment(unit_order, counts)}\n")
		f.write("));\n")

	print(f"Written: {OUT_PATH}")
	print(f"  {max_wave} waves")
	print(f"  {len(rows)} spawn rows")
	print(f"  {len(unit_order)} unit columns")


if __name__ == "__main__":
	main()
